### ISSUE TITLE
Setup unit tests

### ISSUE THREAD

**Issue by rudyeila** [NaseemSrour/Deliveries#24]
We need to begin writing tests. In order to make it easier to do that, we need to first  setup the testing environment (there are some specific things to look for.) The following is the documentation on how to test flask applications:
https://flask.palletsprojects.com/en/master/testing/

**Comment by NaseemSrour** [comment]
I want to put this here as a reminder / motivation:

When we added the basic logger, and replaced all the print statements with it, we wanted of course to test if it works, and as a result we needed to run every piece of code where we used the logger.
If we had unit tests already, we would simply run them and make sure they pass successfully. But we had to test it manually due to lack of unit tests.
This is enough to get a feeling of the importance of units tests, and why we should create new ones as we create more modules in the project.
Hope this helps.

**Comment by rudyeila** [comment]
Yes, and not only that, if you make a little change somewhere, lets say in DBItem, you may break some other features and not notice it. With good test coverage in place, the tests will immediately tell you that you broke something. It is especially essential to have good test coverage prior to refactoring.

**Comment by NaseemSrour** [comment]
100%!
And that's why I believe we should get going on this task early.
I might break it down into sub-tasks.

**Comment by rudyeila** [comment]
Yeah my idea for this task was to simply "setup" the testing, to make it possible to write tests easily. As in setup the flask test client, add configuration of a test database (maybe we'll make this part a different task, since one will need to research that a bit), and maybe setup a test example. That way it will be easy to add new testcases, since all you have to do is look at the example and see how to use the flask testing client. 

Since I have recently done something very similar with Flask and PyTest I can take care of this task.

**Comment by NaseemSrour** [comment]
I'll also read into it.

**Comment by NaseemSrour** [comment]
This is useful: [https://docs.python.org/3/library/unittest.html](https://docs.python.org/3/library/unittest.html)
(it also refers to the 'PyTest' lib that Flask mentions)
